#!/usr/bin/env bash

# Check if at least 3 parameters were passed
if [[ $# -lt 3 ]]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Set the path to the file, IP, username, and path to the SSH key
path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4

# Transfer the file to the user's home directory on the server
scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
