#!/bin/bash

# Install nginx if it's not already installed
if ! command -v nginx &> /dev/null
then
    sudo apt-get update
    sudo apt-get install -y nginx
fi

# Create a new nginx configuration file for the redirection
echo "server {
    listen 80;
    server_name _;
    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
}" | sudo tee /etc/nginx/sites-available/redirect_me > /dev/null

# Enable the new configuration and disable the default configuration
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/
sudo rm /etc/nginx/sites-enabled/default

# Test the configuration and reload nginx
sudo nginx -t && sudo service nginx reload
