#!/usr/bin/env bash
#This script is displaying "best school 10" times using while loop
x=0
while [ $x -lt 10 ]
do
    echo "Best School"
    x=$(( x + 1 ))
    if [[ $x -eq 9 ]]
then
        echo "hi"
    fi	
done
