#!/usr/bin/env bash
#This script loops from 1 to 10 and display some message
x=0
while [ $x -lt 10 ]
do
	x=$(( x + 1 ))
	if [ $x -eq 4 ] 
then
		echo "bad luck"
	elif [ $x -eq 8 ] 
then
		echo "good luck"
	else
		echo "Best School"
	fi
done
