#!/usr/bin/env bash
# display numbers from 1 to 20 using while and case statement and prints badluck from various countries
x=0
while [ $x -lt 20 ]; do
	(( x+=1 ))
	echo "$x"
	case $x in
		4 )
			echo "bad luck from China"
		;;
		9 )
			echo "bad luck from Japan"
		;;
		17 )
			echo "bad luck from Italy"
	esac
done
